config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :comentarios
  resources :qualificacoes
  resources :clientes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  match 'ola' => 'ola_mundo#index', via: 'get'

  resources :restaurantes do
    resources :qualificacoes
  end
  match 'inicio', controller: 'restaurantes', action: 'index', via: 'get'

  root 'restaurantes#index'
end

app/models/comentario.rb
# frozen_string_literal: true

class Comentario < ApplicationRecord
  belongs_to :comentavel, polymorphic: true
end

app/controllers/comentarios_controller.rb
# frozen_string_literal: true

class ComentariosController < ApplicationController
  before_action :set_comentario, only: %i[show edit update destroy]

  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show; end

  # GET /comentarios/new
  def new
    @comentario = Comentario.new
  end

  # GET /comentarios/1/edit
  def edit; end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = Comentario.new(comentario_params)

    respond_to do |format|
      if @comentario.save
        format.html { redirect_back(fallback_location: root_path) }
        format.json { render :show, status: :created, location: @comentario }
      else
        format.html { render :new }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1
  # PATCH/PUT /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario.destroy

    respond_to do |format|
      format.js { redirect_back(fallback_location: root_path) }
		end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comentario
    @comentario = Comentario.find params[:id]
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comentario_params
    params.require(:comentario).permit(:conteudo, :comentavel_id,
      :comentavel_type)
  end
end

app/helpers/comentarios_helper.rb
# frozen_string_literal: true

module ComentariosHelper
end

app/views/comentarios/_comentario.html.erb
<% content_for :css do %>
  <link rel="stylesheet" href="/stylesheets/comentarios.css">
<% end %>
<p id="comentario_<%= comentario.id %>">
  <%= comentario.conteudo %> -
  <%= link_to '(remover)', comentario, method: :delete,
    remote: true, id: "remove_comentario_#{comentario.id}" %>
</p>

app/views/comentarios/_comentarios.html.erb
<div id="comentarios">
  <h3>Comentários</h3>
  <% if comentarios.empty? %>
    Nenhum comentário
  <% else %>
    <%= render comentarios %>
  <% end %>
</div>

app/views/comentarios/_form.html.erb
<%= form_with(model: comentario, local: true) do |form| %>
  <% if comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% comentario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :conteudo %>
    <%= form.text_area :conteudo %>
  </div>

  <div class="field">
    <%= form.label :comentavel_id %>
    <%= form.number_field :comentavel_id %>
  </div>

  <div class="field">
    <%= form.label :comentavel_type %>
    <%= form.text_field :comentavel_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comentarios/_novo_comentario.html.erb
<%= form_for Comentario.new, remote: true do |f| %>
  <%= f.hidden_field :comentavel_id, value: comentavel.id %>
  <%= f.hidden_field :comentavel_type, value: comentavel.class %>

  <%= f.label :conteudo %><br />
  <%= f.text_area :conteudo %>

  <%= f.submit %>
<% end %>

app/views/comentarios/edit.html.erb
<h1>Editing Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

app/views/comentarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comentarios</h1>

<table>
  <thead>
    <tr>
      <th>Conteudo</th>
      <th>Comentavel</th>
      <th>Comentavel type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.conteudo %></td>
        <td><%= comentario.comentavel_id %></td>
        <td><%= comentario.comentavel_type %></td>
        <td><%= link_to 'Show', comentario %></td>
        <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>New Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Back', comentarios_path %>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Conteudo:</strong>
  <%= @comentario.conteudo %>
</p>

<p>
  <strong>Comentavel:</strong>
  <%= @comentario.comentavel_id %>
</p>

<p>
  <strong>Comentavel type:</strong>
  <%= @comentario.comentavel_type %>
</p>

<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>