config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :comentarios
  resources :qualificacoes
  resources :clientes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  match 'ola' => 'ola_mundo#index', via: 'get'

  resources :restaurantes do
    resources :qualificacoes
  end
  match 'inicio', controller: 'restaurantes', action: 'index', via: 'get'

  root 'restaurantes#index'
end

app/controllers/qualificacoes_controller.rb
# frozen_string_literal: true

class QualificacoesController < ApplicationController
  before_action :set_qualificacao, only: %i[show edit update destroy]

  # GET /qualificacoes
  # GET /qualificacoes.json
  def index
    @qualificacoes = Qualificacao.all
  end

  # GET /qualificacoes/1
  # GET /qualificacoes/1.json
  def show; end

  # GET /qualificacoes/new
  def new
    preparar_form

    @qualificacao = Qualificacao.new

    @qualificacao.cliente = Cliente.find(params[:cliente]) if params[:cliente]

    if params[:restaurante]
      @qualificacao.restaurante = Restaurante.find(params[:restaurante])
    end

    respond_to do |format|
      format.html #  new.html.erb
      format.xml { render xml: @qualificacao }
    end
  end

  # GET /qualificacoes/1/edit
  def edit
    preparar_form
  end

  # POST /qualificacoes
  # POST /qualificacoes.json
  def create
    @qualificacao = Qualificacao.new(qualificacao_params)

    respond_to do |format|
      if @qualificacao.save
        format.html { redirect_to @qualificacao, notice: 'Qualificacao was successfully created.' }
        format.json { render :show, status: :created, location: @qualificacao }
      else
        preparar_form
        format.html { render :new }
        format.json { render json: @qualificacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qualificacoes/1
  # PATCH/PUT /qualificacoes/1.json
  def update
    @qualificacao = Qualificacao.find(params[:id])

    respond_to do |format|
      if @qualificacao.update_attributes(qualificacao_params)
        format.html { redirect_to @qualificacao, notice: 'Qualificacao foi atualizada com sucesso.' }
        format.json { head :no_content }
      else
        preparar_form
        format.html { render action: 'edit' }
        format.json { render json: @qualificacao.errors, status: :unprocessable_entity }
        end
    end
  end

  # DELETE /qualificacoes/1
  # DELETE /qualificacoes/1.json
  def destroy
    @qualificacao.destroy
    respond_to do |format|
      format.html { redirect_to qualificacoes_url, notice: 'Qualificacao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_qualificacao
    @qualificacao = Qualificacao.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def qualificacao_params
    params.require(:qualificacao).permit(:cliente_id, :restaurante_id, :nota, :valor_gasto)
  end

  private

  def preparar_form
    @clientes = Cliente.order :nome
    @restaurantes = Restaurante.order :nome
end
end

app/helpers/qualificacoes_helper.rb
# frozen_string_literal: true

module QualificacoesHelper
end

app/views/qualificacoes/_form.html.erb
<%= form_with(model: @qualificacao, local: true) do |form| %>
  <% if @qualificacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(qualificacao.errors.count, "error") %> prohibited this qualificacao from being saved:</h2>

      <ul>
      <% qualificacao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% if @qualificacao.cliente %>
    <%= form.hidden_field 'cliente_id' %>
    <% else %>
    <p><%= form.label :cliente_id %><br />
    <%= form.collection_select(:cliente_id, @clientes, :id, :nome, :prompt => true) %></p>
    <% end %>
  </div>

  <div class="field">
    <% if @qualificacao.restaurante %>
    <%= form.hidden_field 'restaurante_id' %>
    <% else %>
    <p><%= form.label :restaurante_id %><br />
    <%= form.collection_select(:restaurante_id, @restaurantes, :id, :nome, :prompt => true) %></p>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :nota %>
    <%= form.text_field :nota %>
  </div>

  <div class="field">
    <%= form.label :valor_gasto %>
    <%= form.text_field :valor_gasto %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/qualificacoes/edit.html.erb
<h1>Editing Qualificacao</h1>

<%= render 'form', qualificacao: @qualificacao %>

<%= link_to 'Show', @qualificacao %> |
<%= link_to 'Back', qualificacoes_path %>

app/views/qualificacoes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Qualificacoes</h1>

<table>
  <thead>
    <tr>
      <th>Cliente</th>
      <th>Restaurante</th>
      <th>Nota</th>
      <th>Valor gasto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @qualificacoes.each do |qualificacao| %>
      <tr>
        <td><%= qualificacao.cliente.nome %></td>
        <td><%= qualificacao.restaurante.nome %></td>
        <td><%= qualificacao.nota %></td>
        <td><%= valor_formatado(qualificacao.valor_gasto) %></td>
        <td><%= link_to 'Show', qualificacao %></td>
        <td><%= link_to 'Edit', edit_qualificacao_path(qualificacao) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Qualificacao', new_qualificacao_path %>

app/views/qualificacoes/new.html.erb
<h1>Nova qualificação</h1>

<%= render 'form', qualificacao: @qualificacao %>

<%= link_to 'Back', qualificacoes_path %>

app/views/qualificacoes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cliente:</strong>
  <%= @qualificacao.cliente.nome %>
</p>

<p>
  <strong>Restaurante:</strong>
  <%= @qualificacao.restaurante.nome %>
</p>

<p>
  <strong>Nota:</strong>
  <%= @qualificacao.nota %>
</p>

<p>
  <strong>Valor gasto:</strong>
  <%= valor_formatado(@qualificacao.valor_gasto) %>
</p>

<%= link_to 'Edit', edit_qualificacao_path(@qualificacao) %> |
<%= link_to 'Back', qualificacoes_path %>

<%= comentarios @qualificacao %>
<%= novo_comentario @qualificacao %>